In [9]:
from test_methods import test_strain

In [10]:
test_strain()

In [11]:
from pivpy import io, pivpy
data = io.create_sample_field(rows=2,cols=2,noise_sigma=0.0)
data


<xarray.Dataset>
Dimensions:  (x: 2, y: 2, t: 1)
Coordinates:
  * x        (x) int64 32 64
  * y        (y) int64 16 32
  * t        (t) int64 0
Data variables:
    u        (y, x, t) float64 1.0 11.0 1.0 11.0
    v        (y, x, t) float64 -1.0 -1.0 1.0 1.0
    chc      (y, x, t) float64 1.0 1.0 1.0 1.0
Attributes: (2)

In [12]:
data = data.piv.strain()
data

<xarray.Dataset>
Dimensions:  (x: 2, y: 2, t: 1)
Coordinates:
  * x        (x) int64 32 64
  * y        (y) int64 16 32
  * t        (t) int64 0
Data variables:
    u        (y, x, t) float64 1.0 11.0 1.0 11.0
    v        (y, x, t) float64 -1.0 -1.0 1.0 1.0
    chc      (y, x, t) float64 1.0 1.0 1.0 1.0
    w        (y, x, t) float64 0.1133 0.1133 0.1133 0.1133
Attributes: (2)

In [13]:
data.u, data.v, data.w

(<xarray.DataArray 'u' (y: 2, x: 2, t: 1)>
 array([[[ 1.],
         [11.]],
 
        [[ 1.],
         [11.]]])
 Coordinates:
   * x        (x) int64 32 64
   * y        (y) int64 16 32
   * t        (t) int64 0
 Attributes: (1),
 <xarray.DataArray 'v' (y: 2, x: 2, t: 1)>
 array([[[-1.],
         [-1.]],
 
        [[ 1.],
         [ 1.]]])
 Coordinates:
   * x        (x) int64 32 64
   * y        (y) int64 16 32
   * t        (t) int64 0
 Attributes: (1),
 <xarray.DataArray 'w' (y: 2, x: 2, t: 1)>
 array([[[0.11328125],
         [0.11328125]],
 
        [[0.11328125],
         [0.11328125]]])
 Coordinates:
   * x        (x) int64 32 64
   * y        (y) int64 16 32
   * t        (t) int64 0
 Attributes: (2))

In [14]:
import numpy as np 
np.allclose(data["w"].values, 0.11328125, 1e-6)

True

In [15]:
data["w"].mean()

<xarray.DataArray 'w' ()>
array(0.11328125)
Attributes: (2)

In [16]:
data["w"].attrs

{'units': '1/dt', 'standard_name': 'strain'}

In [17]:
from test_methods import test_vec2scal

In [18]:
test_vec2scal()

In [19]:
data = io.create_sample_Dataset()

In [20]:
data = data.piv.vec2scal("vort")

In [21]:
data

<xarray.Dataset>
Dimensions:  (x: 3, y: 5, t: 5)
Coordinates:
  * x        (x) int64 32 64 96
  * y        (y) int64 16 32 48 64 80
  * t        (t) int64 0 1 2 3 4
Data variables:
    u        (y, x, t) float64 1.0 1.0 1.0 1.0 1.0 ... 11.0 11.0 11.0 11.0 11.0
    v        (y, x, t) float64 -1.0 -1.0 -1.0 -1.0 -1.0 ... 1.0 1.0 1.0 1.0 1.0
    chc      (y, x, t) float64 1.0 1.0 1.0 1.0 1.0 1.0 ... 1.0 1.0 1.0 1.0 1.0
    w        (y, x, t) float64 0.0 0.0 0.0 0.0 0.0 0.0 ... 0.0 0.0 0.0 0.0 0.0
Attributes: (2)