In [72]:
""" tests pivpy.pivpy methods """
import pathlib
import numpy as np
import pkg_resources as pkg
import pytest
from pivpy import io


FILE1 = "Run000001.T000.D000.P000.H001.L.vec"
FILE2 = "Run000002.T000.D000.P000.H001.L.vec"
path = pathlib.Path(pkg.resource_filename("pivpy", "data"))
path = path / "Insight"


_a = io.load_vec(path / FILE1)
_b = io.load_vec(path / FILE2)

In [73]:
data = io.create_sample_field(rows=3, cols=3, noise_sigma=0.0)

In [74]:
data.piv.set_scale(1/16)

<xarray.Dataset>
Dimensions:  (x: 3, y: 3, t: 1)
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
  * t        (t) int64 0
Data variables:
    u        (y, x, t) float64 0.0625 0.375 0.6875 ... 0.0625 0.375 0.6875
    v        (y, x, t) float64 -0.0625 -0.0625 -0.0625 ... 0.0625 0.0625 0.0625
    chc      (y, x, t) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
Attributes: (2)

In [75]:
data

<xarray.Dataset>
Dimensions:  (x: 3, y: 3, t: 1)
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
  * t        (t) int64 0
Data variables:
    u        (y, x, t) float64 0.0625 0.375 0.6875 ... 0.0625 0.375 0.6875
    v        (y, x, t) float64 -0.0625 -0.0625 -0.0625 ... 0.0625 0.0625 0.0625
    chc      (y, x, t) float64 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0 1.0
Attributes: (2)

In [76]:
data.isel(t=0)["u"]

<xarray.DataArray 'u' (y: 3, x: 3)>
array([[0.0625, 0.375 , 0.6875],
       [0.0625, 0.375 , 0.6875],
       [0.0625, 0.375 , 0.6875]])
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
    t        int64 0
Attributes: (1)

In [77]:

data["u"].differentiate("x")

<xarray.DataArray 'u' (y: 3, x: 3, t: 1)>
array([[[0.3125],
        [0.3125],
        [0.3125]],

       [[0.3125],
        [0.3125],
        [0.3125]],

       [[0.3125],
        [0.3125],
        [0.3125]]])
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
  * t        (t) int64 0

In [80]:
data["v"].differentiate("y")

<xarray.DataArray 'v' (y: 3, x: 3, t: 1)>
array([[[0.125],
        [0.125],
        [0.125]],

       [[0.125],
        [0.125],
        [0.125]],

       [[0.125],
        [0.125],
        [0.125]]])
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
  * t        (t) int64 0

In [82]:
data.piv.strain()["w"]

<xarray.DataArray 'w' (y: 3, x: 3, t: 1)>
array([[[0.11328125],
        [0.11328125],
        [0.11328125]],

       [[0.11328125],
        [0.11328125],
        [0.11328125]],

       [[0.11328125],
        [0.11328125],
        [0.11328125]]])
Coordinates:
  * x        (x) float64 1.0 2.0 3.0
  * y        (y) float64 0.5 1.0 1.5
  * t        (t) int64 0
Attributes: (2)

In [78]:
def test_strain():
    """tests shear estimate"""
    data = io.create_sample_field(rows=2, cols=2, noise_sigma=0.0)
    data = data.piv.strain()
    print(data["u"])
    print(data["v"])
    print(data["w"])
    assert np.allclose(data["w"].values, 0.11328125, 1e-6)

In [79]:
test_strain()

<xarray.DataArray 'u' (y: 2, x: 2, t: 1)>
array([[[ 1.],
        [11.]],

       [[ 1.],
        [11.]]])
Coordinates:
  * x        (x) int64 16 32
  * y        (y) int64 8 16
  * t        (t) int64 0
Attributes: (1)
<xarray.DataArray 'v' (y: 2, x: 2, t: 1)>
array([[[-1.],
        [-1.]],

       [[ 1.],
        [ 1.]]])
Coordinates:
  * x        (x) int64 16 32
  * y        (y) int64 8 16
  * t        (t) int64 0
Attributes: (1)
<xarray.DataArray 'w' (y: 2, x: 2, t: 1)>
array([[[0.453125],
        [0.453125]],

       [[0.453125],
        [0.453125]]])
Coordinates:
  * x        (x) int64 16 32
  * y        (y) int64 8 16
  * t        (t) int64 0
Attributes: (2)


AssertionError: 